### ISSUE TITLE
Games before 1999 

### ISSUE THREAD

**Issue by MinscyBubu** [TesterTesterov/AI5WINScriptTool#1]
There's a chance to make this tool compatibility with older games?

For example, in Isaku (1997 release), the tool can't decompile the scripts:

![imagen](https://user-images.githubusercontent.com/88146930/147947186-1c4e70b6-de66-4a71-bdab-f33014254002.png)

I can provide you the .mes files of this game if you need it!

**Comment by TesterTesterov** [comment]
@MinscyBubu, I can make the tool support older games, just give me the scripts. Don't know how much time it'll take, though. It depends on difficulty and difference.

**Comment by MinscyBubu** [comment]
Isaku (1997) scripts:

[MES.zip](https://github.com/TesterTesterov/AI5WINScriptTool/files/7806971/MES.zip)

**Comment by TesterTesterov** [comment]
Are thou really sure Isaku (1997) is on AI5WIN? Can you show an ,exe screen?
Scripts looks quite... erm... abnormal for AI5WIN.

**Comment by TesterTesterov** [comment]
It really may take some time, since it is very different, have new strings encryption and other problems. I really did not think that scripts in one engine can be so different. Basically, it seems like AI5WIN was forced to support scripts from previous engines, like AI4 or AI3.

**Comment by MinscyBubu** [comment]
Here you go:

![imagen](https://user-images.githubusercontent.com/88146930/148082472-011137d4-5f30-4d8f-aab4-eeff75d972d7.png)

**Comment by TesterTesterov** [comment]
It is AI5WIN indeed... I'll support it then I'll have time, since it is no-priority (there are different versions of the game as well), since it supposes to be quite time-consuming. Basically, I'd need to hack the script system almost from the scratch and somehow support it in the current tool.

**Comment by TesterTesterov** [comment]
@MinscyBubu, okay, I got some testing right now. Well, the version of AI5WIN you got me **is hackable**, but it would be quite troublesome to hack. I would definitely need to hack the exe of the game.

First, the scripts itself are quite exotic. Their structures would be tiresome to hack.

Next, I got did some string cryptoanalysis. The algorithm is about as following...
- The engine read one byte. 
- - If it is < 0x81, then it prints this byte + 0x20 and the next byte.
- - If it is not, it does some operation and prints two bytes. I don't sure about the operation yet, since it is not as simple as in Silky Engine. I would need to analyze this more.
But some of its results are...
_E3 -> 82 C8
11100011 -> 1000001011001000.
E7 -> 82 A2
11100111 -> 1000001010100010.
E8 -> 82 A6
11101000 -> 1000001010100110.
F2 -> 81 41
11110010 -> 1000000101000001.
F6 -> 82 C4
11110110 -> 1000001011000100.
F7 -> 82 CD
11110111 -> 1000001011001101._

===
And the main point. This version of engine is either in one ([Isaku 1997](https://vndb.org/r4567)) or in two (with [this one](https://vndb.org/r4590), but I am not sure) releases. And both games has more modern engines/versions. For example, this tool does work with [Isaku Renewal](https://vndb.org/r4568).

**Therefore I do not see reasons to hack this specific version, as it is quite problematic and very different from any others. I would, if there would be games only with this version of AI5WIN, but every game with this heretic version has a release with different version as well.**

If you do not have any objections, I will close the issue. If you want to work with Isaku, take [Isaku Renewal](https://vndb.org/r4568) instead.
