### ISSUE TITLE
Isaku Renewal message breaks

### ISSUE THREAD

**Issue by zsolszesz** [TesterTesterov/AI5WINScriptTool#2]
Hey,
I am trying to translate Isaku Renewal, which I got from here: https://archive.org/details/isaku-renewal/ . I was able to edit the texts inside OPENIN.MES, and the game starts that way, but it only works with full-width characters, so the message box quickly fills up.
I tried using the commands you mentioned in the documentation to put message breaks, but unfortunately, they don't work with this game. I also tried this:
```
#1-CALL
[
    [
        "*STRUCT*",
        "RAW",
        2,
        "RAW",
        2,
        "STRUCT_END",
        []
    ],
    [
        "*GROUP*"
    ]
]
```
Since this is what the game is using between two texts. However, it crashes immediately after starting a new game.
I was hoping you could tell me which commands I should use to put message breaks.

Also, something that's unnecessary for this case but you might be interested in it. On the juice script they mentioned that on the PC98 versions of AI5WIN, you could edit the system variable with index 21, to make the game use half-width characters: https://github.com/tomyun/juice/tree/main/mes#font-width .
I was wondering if this was possible on Windows versions with your tool.

I appreciate any help you can provide.

**Comment by TesterTesterov** [comment]
Hello. I have tested that Isaku Renewal and it just **does not launch in my computer at all**. I shall try to give you an advice, based on the theory, but I cannot test for myself because of aforementioned reason.

As for message breaks, that command **did** work when I tried it to a game with 0 version of AI5WIN which have worked in my environment (there was one game like this, but I don't remember which one it exactly was). As for crashes... Did it crash only after you reinserted the changed script in the game? Or did it crash just after you reinserted any script?

As for changing font weight... Try to find commands with 21/512/16/528.

Alas, without testing personally, it is not much I can do here. It is possible that it may be somewhat different variation of 0 version, that's why it does not work, but I have no way to check.

**Comment by zsolszesz** [comment]
Well it uses a ustandard archive, so it might be similar to Doukyuusei 2? I don't have that game so I'm not sure.
As for the 0 version game you tested, which command worked there? The one you wrote in the documentation or the one I pasted in my comment? For me, the game immediately crashes as soon as I reach the part that uses OPENIN.mes, even if I try to put the message break somewhere at the end of the file.

**Comment by zsolszesz** [comment]
Alright, I managed to do it. I haven't been able to figure out how to make the game support half-width fonts yet, but the message break was a dumb mistake on my end. I kept naming the file as OPENIN.mes, but it's case sensitive and the game expected OPENIN.MES. Now message breaks are working with the commands I pasted in my original comment. Sorry for bothering you with this, and thanks for trying to help.
