### ISSUE TITLE
2, "Shangrlia Multipack, etc. ~ 2005 y."  not insert

### ISSUE THREAD

**Issue by kangmeiyuanchao** [TesterTesterov/AI5WINScriptTool#3]
when I click Compile button，It will showe error: non-hexadecimal number found in fromhex（） arg at position 0
![图片](https://github.com/TesterTesterov/AI5WINScriptTool/assets/89840896/39c2b360-bd4e-4ac5-b60a-585bfc1c1e4c)

game is Jokei Kazoku ~Inbou~
https://vndb.org/v3327

**Comment by TesterTesterov** [comment]
@kangmeiyuanchao, post here the script or scripts which have the problem. In the MES format.

**Comment by kangmeiyuanchao** [comment]
![图片](https://github.com/TesterTesterov/AI5WINScriptTool/assets/89840896/726154cd-12ef-45d3-a0d1-faf6fdf8c03c)


[mes.zip](https://github.com/TesterTesterov/AI5WINScriptTool/files/11607101/mes.zip)

**Comment by TesterTesterov** [comment]
@kangmeiyuanchao, ah, indeed... So *that* was the problem...

Okay, try [1.1 release](https://github.com/TesterTesterov/AI5WINScriptTool/releases/tag/1.1).

===
*Note: Previously decompiled scripts somewhat incompatible with the previous ones. In order to make them compatible, you need to delete some mismatching code in the beginning of the old ones.*

**Comment by kangmeiyuanchao** [comment]
Thank you very much
